require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArrangedAcupuncturePointsController do

  # This should return the minimal set of attributes required to create a valid
  # ArrangedAcupuncturePoint. As you add validations to ArrangedAcupuncturePoint, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArrangedAcupuncturePointsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all arranged_acupuncture_points as @arranged_acupuncture_points" do
      arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:arranged_acupuncture_points).should eq([arranged_acupuncture_point])
    end
  end

  describe "GET show" do
    it "assigns the requested arranged_acupuncture_point as @arranged_acupuncture_point" do
      arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
      get :show, {:id => arranged_acupuncture_point.to_param}, valid_session
      assigns(:arranged_acupuncture_point).should eq(arranged_acupuncture_point)
    end
  end

  describe "GET new" do
    it "assigns a new arranged_acupuncture_point as @arranged_acupuncture_point" do
      get :new, {}, valid_session
      assigns(:arranged_acupuncture_point).should be_a_new(ArrangedAcupuncturePoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested arranged_acupuncture_point as @arranged_acupuncture_point" do
      arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
      get :edit, {:id => arranged_acupuncture_point.to_param}, valid_session
      assigns(:arranged_acupuncture_point).should eq(arranged_acupuncture_point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArrangedAcupuncturePoint" do
        expect {
          post :create, {:arranged_acupuncture_point => valid_attributes}, valid_session
        }.to change(ArrangedAcupuncturePoint, :count).by(1)
      end

      it "assigns a newly created arranged_acupuncture_point as @arranged_acupuncture_point" do
        post :create, {:arranged_acupuncture_point => valid_attributes}, valid_session
        assigns(:arranged_acupuncture_point).should be_a(ArrangedAcupuncturePoint)
        assigns(:arranged_acupuncture_point).should be_persisted
      end

      it "redirects to the created arranged_acupuncture_point" do
        post :create, {:arranged_acupuncture_point => valid_attributes}, valid_session
        response.should redirect_to(ArrangedAcupuncturePoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved arranged_acupuncture_point as @arranged_acupuncture_point" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArrangedAcupuncturePoint.any_instance.stub(:save).and_return(false)
        post :create, {:arranged_acupuncture_point => {}}, valid_session
        assigns(:arranged_acupuncture_point).should be_a_new(ArrangedAcupuncturePoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArrangedAcupuncturePoint.any_instance.stub(:save).and_return(false)
        post :create, {:arranged_acupuncture_point => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested arranged_acupuncture_point" do
        arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
        # Assuming there are no other arranged_acupuncture_points in the database, this
        # specifies that the ArrangedAcupuncturePoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArrangedAcupuncturePoint.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => arranged_acupuncture_point.to_param, :arranged_acupuncture_point => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested arranged_acupuncture_point as @arranged_acupuncture_point" do
        arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
        put :update, {:id => arranged_acupuncture_point.to_param, :arranged_acupuncture_point => valid_attributes}, valid_session
        assigns(:arranged_acupuncture_point).should eq(arranged_acupuncture_point)
      end

      it "redirects to the arranged_acupuncture_point" do
        arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
        put :update, {:id => arranged_acupuncture_point.to_param, :arranged_acupuncture_point => valid_attributes}, valid_session
        response.should redirect_to(arranged_acupuncture_point)
      end
    end

    describe "with invalid params" do
      it "assigns the arranged_acupuncture_point as @arranged_acupuncture_point" do
        arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArrangedAcupuncturePoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => arranged_acupuncture_point.to_param, :arranged_acupuncture_point => {}}, valid_session
        assigns(:arranged_acupuncture_point).should eq(arranged_acupuncture_point)
      end

      it "re-renders the 'edit' template" do
        arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArrangedAcupuncturePoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => arranged_acupuncture_point.to_param, :arranged_acupuncture_point => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested arranged_acupuncture_point" do
      arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
      expect {
        delete :destroy, {:id => arranged_acupuncture_point.to_param}, valid_session
      }.to change(ArrangedAcupuncturePoint, :count).by(-1)
    end

    it "redirects to the arranged_acupuncture_points list" do
      arranged_acupuncture_point = ArrangedAcupuncturePoint.create! valid_attributes
      delete :destroy, {:id => arranged_acupuncture_point.to_param}, valid_session
      response.should redirect_to(arranged_acupuncture_points_url)
    end
  end

end
